hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("[workspace 10 silent] ghostty -e quickshell")
    hl.exec_cmd("[workspace 1 silent] zed")
    hl.exec_cmd("[workspace 2 silent] firefox")
end)

hl.config({
    autogenerated = false,
    xwayland = { force_zero_scaling = true },
    input = {
        kb_layout = "de",
        kb_options = "ctrl:nocaps",
        numlock_by_default = true,
        follow_mouse = 1,
        accel_profile = "flat",
        touchpad = {
            tap_to_click = true,
            natural_scroll = true,
        },
    },
    general = {
        layout = "dwindle",
    },
    decoration = {
        active_opacity = 0.9,
        inactive_opacity = 0.8,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(00000070)",
        },
        blur = {
            enabled = true,
            size = 10,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    dwindle = {
        preserve_split = true,
        force_split = 2,
    },
})

local function is_connected(monitor_name)
    local cmd = "grep -l '^connected$' /sys/class/drm/*" .. monitor_name .. "/status 2>/dev/null"
    local handle = io.popen(cmd)
    if handle then
        local output = handle:read("*a")
        handle:close()
        return output ~= nil and output ~= ""
    end
    return false
end

local has_dp1 = is_connected("DP-1")
local has_dp2 = is_connected("DP-2")
local has_edp1 = is_connected("eDP-1")

for i = 1, 10 do
    if has_dp1 and has_dp2 then
        if i <= 5 then
            hl.workspace_rule({ workspace = tostring(i), monitor = "DP-1", default = (i == 1) })
        else
            hl.workspace_rule({ workspace = tostring(i), monitor = "DP-2", default = (i == 6) })
        end
    elseif has_edp1 then
        hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1", default = (i == 1) })
    end
end

-- Animations
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

require("modules.colors")
require("modules.outputs")
require("modules.layout")
require("modules.env")
require("modules.binds")
require("modules.windowrules")
require("modules.hyprglass")
