-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")

hl.config({
    xwayland = { force_zero_scaling = true },
    input = {
        kb_layout = "de",
        numlock_by_default = true,
        follow_mouse = 1,
        accel_profile = "flat",
        touchpad = {
            tap_to_click = true,
            natural_scroll = true,
        },
    },
    general = {
        border_size = 2,
        layout = "dwindle",
    },
    decoration = {
        active_opacity = 0.75,
        inactive_opacity = 0.7,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(00000070)",
        },
        blur = {
            enabled = true,
            size = 10,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    dwindle = {
        preserve_split = true,
        force_split = 2,
    },
    master = {
        mfact = 0.5,
    },
})

-- Assing workspaces 1-5 to monitor DP-1 and workspaces 6-10 to monitor DP-2
for i = 1, 10 do
    if i <= 5 then
        hl.workspace_rule({ workspace = tostring(i), monitor = "DP-1" })
    else
        hl.workspace_rule({ workspace = tostring(i), monitor = "DP-2" })
    end
end

-- Animations
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

-- DMS
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
