hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("[workspace 10 silent] ghostty -e quickshell")
end)

hl.config({
    autogenerated = false,
    xwayland = { force_zero_scaling = true },
    input = {
        kb_layout = "de",
        kb_options = "ctrl:nocaps",
        numlock_by_default = true,
        follow_mouse = 1,
        accel_profile = "flat",
        touchpad = {
            tap_to_click = true,
            natural_scroll = true,
        },
    },
    general = {
        layout = "dwindle",
    },
    decoration = {
        active_opacity = 0.75,
        inactive_opacity = 0.7,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(00000070)",
        },
        blur = {
            enabled = true,
            size = 10,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    dwindle = {
        preserve_split = true,
        force_split = 2,
    },
})

-- Query monitors registered by Hyprland
local handle = io.popen("hyprctl monitors all")
local monitors_output = handle:read("*a")
handle:close()

-- Escape the '-' character with '%' for Lua pattern matching
local has_dp1 = string.find(monitors_output, "DP%-1")
local has_dp2 = string.find(monitors_output, "DP%-2")
local has_edp1 = string.find(monitors_output, "eDP%-1")

for i = 1, 10 do
    if has_dp1 and has_dp2 then
        if i <= 5 then
            local is_default = (i == 1)
            hl.workspace_rule({ workspace = tostring(i), monitor = "DP-1", default = is_default })
        else
            local is_default = (i == 6)
            hl.workspace_rule({ workspace = tostring(i), monitor = "DP-2", default = is_default })
        end
    elseif has_edp1 then
        local is_default = (i == 1)
        hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1", default = is_default })
    end
end

-- Animations
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

require("modules.colors")
require("modules.outputs")
require("modules.layout")
require("modules.env")
require("modules.binds")
require("modules.windowrules")
